[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://mirthday-production-23f7.up.railway.app"

[context.deploy-preview.environment]
  VITE_API_URL = "https://mirthday-production-23f7.up.railway.app"

[context.branch-deploy.environment]
  VITE_API_URL = "https://mirthday-production-23f7.up.railway.app"
