[build]
  command = "npm install && npx prisma generate && npx prisma migrate deploy"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "20.19.0"

[[functions]]
  directory = "netlify/functions"
  node_bundler = "esbuild"
